Updated Communication and Inclusivity Sections
UBC-iGEM/internal-wiki-2023-24 pull request #45
Opened 2024-03-12 02:44 UTC by yejonlhee

Made new sections and updated internal wiki elements for communications and inclusivity.

2024-03-12 03:29 UTC, lhao03 commented
There's random capitalization and missing periods, are these sections meant to be bulleted lists? 
![image](https://github.com/UBC-iGEM/internal-wiki-2023-24/assets/55033656/7cdad900-68f1-403c-8fa1-fca5de143557)

2024-03-12 03:31 UTC, lhao03 requested changes

2024-03-12 03:31 UTC, lhao03 commented on src/human-practices/communication/blog.md
> +Encourage members to partake in a team-wide activity
To make this a list, add `-` before each point:

```
- point 1
- point 2
```

you will get 

- point 1
- point 2

2024-03-13 02:06 UTC, lhao03 approved these changes

2024-03-13 06:36 UTC, jxin04 approved these changes

2024-03-13 06:36 UTC, jxin04 approved these changes

2024-03-13 06:42 UTC, jxin04 approved these changes

2024-03-13 06:42 UTC, jxin04 approved these changes

2024-03-13 06:42 UTC, jxin04 approved these changes

2024-03-13 15:19 UTC, merged