Harrison Initial commit
UBC-iGEM/internal-wiki-2023-24 pull request #46
Opened 2024-03-12 03:19 UTC by Maestro0202

2024-03-12 03:30 UTC, lhao03 commented
Random capitalization and missing periods, are these sections meant to be bulleted lists? 
![image](https://github.com/UBC-iGEM/internal-wiki-2023-24/assets/55033656/b0f4051a-6c4c-44b9-b7ba-6f89f7b97f61)

2024-03-12 03:31 UTC, lhao03 requested changes

2024-03-12 03:31 UTC, lhao03 commented on src/human-practices/education/lets-talk-science.md
> +Executing our program with classroom visits
To make this a list, add `-` before each point:

```
- point 1
- point 2
```

you will get 

- point 1
- point 2

2024-03-13 01:46 UTC, lhao03 approved these changes

2024-03-13 06:34 UTC, jxin04 requested changes
if these are bullet points, remove periods at the end and remove capitals for words in the middle

2024-03-14 14:05 UTC, lhao03 reviewed
Please double check all bullet points!

2024-03-14 14:05 UTC, lhao03 commented on src/human-practices/sustainability/sustainability.md
> +- Reach out to previous guests who have been on the podcast before as well as new voices and experts who can bring unique perspectives to the podcast.
remove period here

2024-03-14 14:05 UTC, lhao03 commented on src/human-practices/sustainability/sustainability.md
> +- To venture into discussions that do not have a clear link to these areas.
remove period here

2024-03-14 14:05 UTC, lhao03 commented on src/human-practices/education/lets-talk-science.md
> +- Marketing and Branding
lowercase the "b" in branding; these are just some issues I saw at a glance, please check if there are any more!

2024-03-15 19:39 UTC, lhao03 requested changes

2024-03-15 19:39 UTC, lhao03 commented on src/human-practices/sustainability/sustainability.md
> +- To gain valuable relationships with influential Health Professionals
Lowercase the "H" in health professionals

2024-03-15 19:39 UTC, lhao03 commented on src/human-practices/sustainability/sustainability.md
> +- Figure out how to enhance production quality (Better question, recording, editing, design, etc)
Lowercase "B" in better

2024-03-15 19:48 UTC, lhao03 approved these changes
Thanks!

2024-03-16 00:48 UTC, jxin04 approved these changes

2024-03-16 00:51 UTC, merged