Thermostable TdT Page initial update
UBC-iGEM/internal-wiki-2023-24 pull request #48
Opened 2024-03-13 01:32 UTC by TunaW

2024-03-13 02:03 UTC, dperezhi commented
For the "ssDNA to dsDNA Experimental Design" part, the Context and Scope section needs a reference. If you want, try using the Bibliography format Lucy set up, it's pretty nice; to see how it is set up check the Microfluidics index.md file as well as the bibliography.bib file (within the src folder).

2024-03-13 02:10 UTC, lhao03 commented
I have to add the necessary packages to the replit setup; so right now the bibliography.bib doesn't work on replit (but does work on Codespaces)

2024-03-13 04:04 UTC, lhao03 commented
But for now, like Diego mentioned, you can add references through bibliography.bib, they just won't render correctly

2024-03-13 06:19 UTC, lhao03 commented
I merged main/resolved some merge conflicts so you can now add sources to bibliography.bib. Make sure to `git pull` before adding new commits since I pushed some changes. Thanks!

2024-03-13 17:12 UTC, dperezhi reviewed
ssDNA to dsDNA Experimental Design, context and scope, needs a reference

2024-03-14 15:47 UTC, lhao03 requested changes

2024-03-18 01:44 UTC, BurakMOzkan requested changes
Some grammar mistakes. I recommend having key words and then a dash to further explain in detail the addition. Great work otherwise!

2024-03-18 02:58 UTC, lhao03 commented on src/wet-lab/design/tdt-experiment.md
> +Liang, X., Kuhn, H., & Frank-Kamenetskii, M. D. (2006). Monitoring single-stranded DNA secondary structure formation by determining the topological state of DNA catenanes. Biophysical Journal, 90(8),
https://github.com/UBC-iGEM/internal-wiki-2023-24/blob/2073b9308f77212a04f615918a17f7db0e55ded0/src/bibliography.bib#L19-L30

2024-03-18 02:58 UTC, lhao03 commented on src/wet-lab/design/tdt-experiment.md
> +Liang, X., Kuhn, H., & Frank-Kamenetskii, M. D. (2006). Monitoring single-stranded DNA secondary structure formation by determining the topological state of DNA catenanes. Biophysical Journal, 90(8),
https://github.com/UBC-iGEM/internal-wiki-2023-24/blob/073f715ae595a904d7102099ebbb248b28afde57/src/bibliography.bib#L167-L180

2024-03-20 04:35 UTC, lhao03 commented on src/bibliography.bib
> +@article{TdT background,
```suggestion
@article{TdT_background,
```

Sorry need dash here, but not for `@Comment TdT Experiment`

2024-03-20 04:36 UTC, lhao03 commented on src/wet-lab/design/tdt-experiment.md
> +Liang, X., Kuhn, H., & Frank-Kamenetskii, M. D. (2006). Monitoring single-stranded DNA secondary structure formation by determining the topological state of DNA catenanes. Biophysical Journal, 90(8),
```suggestion
[@TdT_background]
```

2024-03-20 15:17 UTC, lhao03 approved these changes
I'll merge this in for now, but open an issue stating the changes requested, since the TdT plans are changing, so everyone can start reading about the wet lab plans.

2024-03-20 15:17 UTC, merged